version: "3"
service:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    network:
      - network1
  db:
    build: ./db_dockerfile
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    network:
      - network1
networks:
  network1:
     driver: custom-driver-1


