version: "3"
networks:
  my_network:


services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - my_network

  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network

